### DISCUSSION TITLE
Parse embedded language which is blocked-off, not delimited

### DISCUSSION THREAD

**Discussion by mamachanko** [tree-sitter/tree-sitter#2007] [Q&A]
`ytt` is a templating language for YAML. While it's sometimes described as _"YAML with Python"_ it's actually more accurate to say _"YAML with a [Starlark](https://github.com/google/starlark-go/blob/master/doc/spec.md)-dialect in comments"_.

For example:

```yaml
#@ def stuff():
#@   return ['cool', 'items']
#@ end

---
items: #@ stuff()

---
louder_items:
  #@ for item in stuff():
  - #@ "{}!".format(item)
  #@ end
```

yields:

```
---
items:
- cool
- items
---
louder_items:
- cool!
- items!
```

As you can see, Starlark statements and expressions are blocked off by `#@`, e.g. the definition of the `stuff` function.

Let's say I would want to write a grammar for the purpose of highlighting and for the use within a language server. The Starlark blocks should be highlighted and represented within the tree. I struggle to discern if this is practically possible. Ideally I would be able to interact with a tree that contains the YAML nodes and Starlark blocks.

I have looked at plenty of grammars, discussions and issues but I can't get across the problem which is presented by `#@` blocks.

I don't think I can use injection for highlighting. Neither am I sure about writing a grammar.

---
p.s.: `tree-sitter` ❤️
