### DISCUSSION TITLE
Are compile time kind and field ids available for the Rust bindings?

### DISCUSSION THREAD

**Discussion by VonTum** [tree-sitter/tree-sitter#3269] [Q&A]
Well, as the title states. 

Is there some way to get compile time values for the kind and field ids for my custom language? This would allow the Rust optimizer to make much more efficient branch jump tables for compilers using tree-sitter as a compiler frontend. 

Currently I am using the second-best option, namely simply requesting all ids ahead of time and storing them in a static data structure: https://github.com/pc2/sus-compiler/blob/3a3a5c9dfe5c5eeb8fde6ec7f49823af60d37f49/src/parser.rs#L84-L230

**Comment by WillLillis** [comment]
It doesn't appear to be possible with the current API. The rust binding `id_for_node_kind()` calls the C function `ts_language_symbol_for_name()`, which iterates through all of the given language's symbols and checks for a match via string comparison:

https://github.com/tree-sitter/tree-sitter/blob/cbcb51b8575ca58f8bfde4f5e78cd08d562faa81/lib/src/language.c#L113-L130

I'm sure there's plenty of hacky ways you could have these values available at compile time, but I imagine that would make changing to a different version of the grammar to be quite difficult and/or messy. In the past I tried looking at the generated code to have the node values known beforehand, but they didn't match up with the values returned at runtime. It was suggested to me in [this issue](https://github.com/tree-sitter/tree-sitter/issues/2768) to just use the `Language::node_kind_for_id()` and/or the `Language::id_for_node_kind()` methods.

**Reply by VonTum** [reply]
Well, I am using these methods already, I'm looking to move to a compiletime approach. This isn't just useful from an optimization standpoint, but also in utility. For instance the runtime fields can't be used in a `match` context. 

I don't quite see the argument about how changing to a different version of the grammar would mess things up honestly. If the field and kind ids are requested at compile time, and every change to the language grammar requires a recompile, then they should always stay in sync. 

I'll look into building a rust proc macro to request the ids. That might even make everything quite a bit cleaner compared to the `SUS.my_this_that_field` everywhere.

**Reply by VonTum** [reply]
But in any case, would it not be nice to just have the compile-time values as `const` globals in the generated bindings file?

**Reply by WillLillis** [reply]
> I don't quite see the argument about how changing to a different version of the grammar would mess things up honestly. If the field and kind ids are requested at compile time, and every change to the language grammar requires a recompile, then they should always stay in sync.

I meant this in reference to doing something hacky, like hardcoding in the kind ids as your own global `const` values or something similar. If the values were grabbed at compile time this definitely wouldn't be an issue. Sorry I wasn't clearer!

> I'll look into building a rust proc macro to request the ids

This would be very cool, I'm excited to see what this looks like :)

> But in any case, would it not be nice to just have the compile-time values as const globals in the generated bindings file?

Completely agree, it would be really nice! I'll try to take a look and see how difficult it would be to implement.

**Reply by VonTum** [reply]
It was actually surprisingly easy to do with proc_macros. I've added the code [here](https://github.com/pc2/sus-compiler/blob/330a4d028cdb196ea5bea92d41994b13464c8f90/sus_proc_macro/src/lib.rs). This code is of course specific to the SUS language, but it doesn't need to be. 

It seems like a generic enough thing that it could really be really nice as a builtin feature of the generated rust bindings for tree-sitter. 

To use it, one can simply use `kind!("statement")`, `field!("name")`, `kw!("for")` etc.

**Reply by VonTum** [reply]
And now I've been able to replace two `match` statements over program text, with match statements over `cursor.kind_id()`: https://github.com/pc2/sus-compiler/commit/d693030d63a76045fd6cabe47899a6eff90fbc98

**Reply by WillLillis** [reply]
> It was actually surprisingly easy to do with proc_macros. I've added the code [here](https://github.com/pc2/sus-compiler/blob/330a4d028cdb196ea5bea92d41994b13464c8f90/sus_proc_macro/src/lib.rs). This code is of course specific to the SUS language, but it doesn't need to be.

Wow, this is great! I haven't worked with proc macros too much (yet) but I expected implementing this to be a lot more complicated. I'd love it if you opened up a PR to have this functionality added to the core library. :)

**Reply by VonTum** [reply]
Hmm, I've been mulling it over, but I'm not finding a good place to fit the proc_macros into the generated crate. To start, it's not possible I believe to add them to the core library, because they require to be statically linked to the user-provided language, such that the compiler can access it. 

The problem is that rust doesn't allow a crate to have both regular code, and proc_macros in the same crate. 

I've thought to create a new folder in the generated project: `bindings/rust/tree-sitter-PARSER_NAME-proc/Cargo.toml` and `bindings/rust/tree-sitter-PARSER_NAME-proc/lib.rs`, but using it will then be rather ugly and brittle. 

The user's Cargo.toml would then look something like this:
```toml
[dependencies]
tree-sitter-sus = {path = "path/to/sus"}
tree-sitter-sus-proc = {path = "path/to/sus/bindings/rust/tree-sitter-sus-proc"}
```

It seems nasty to have to reach down into the bindings folder. If you have any ideas?

**Reply by WillLillis** [reply]
I also tried adding it to the core and wasn't able to get anywhere. I haven't done much work with rust's macros though, so maybe I'm missing something?

I also tried your approach by adding another crate inside the bindings folder  of a grammar and while that works I agree that it's a bit awkward/ brittle. Maybe another option would be to generate a `tree-sitter-GRAMMAR_NAME-proc` crate outside of the bindings directory? It could be published as a separate crate that then depends on `tree-sitter-GRAMMAR_NAME`. I was able to create a `tree-sitter-c-proc` crate with your macros, have it depend on the regular `tree-sitter-c` crate, and then add all of these dependencies to a sample program with the following Cargo.toml:

```toml
[package]
name = "ts_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.22.2"
tree-sitter-c = "0.20.7"
tree-sitter-c-proc = { path = "/home/lillis/projects/tree-sitter-c-proc/" }
```

Of course once `tree-sitter-c-proc` (or any other grammar's proc variant) is published to crates.io we wouldn't have to specify a local path. 

Maybe it would be good to open an issue and ask the maintainers for their thoughts? I've taken a look at the code used to generate the rust bindings and it doesn't look too bad to add to.

**Reply by VonTum** [reply]
So a major thing here too is that I believe generally subdirectories of Cargo projects should be dependencies of the main project, but in this case, the proc_macro library wants to depend on the main library. Maybe I just got it wrong, but in the proc macro's Cargo.toml, I had to make it depend on the parent like this:

```toml
[package]
name = "proc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]

tree-sitter-testtree = {path = "../../.."}

tree-sitter = ">=0.22.2"

# proc_macro utils
syn = "1.0"
quote = "1.0"

```
You did it with an absolute path I see. 

I don't quite know if the other maintainers would very much like an extra directory there either, like philosophically rust stuff should go in bindings/rust. 

With a single subdirectory, it's more direct, and nicer to use but it'll still have to depend with `path = ".."`

Maybe we can just turn this discussion itself into an issue?

Also perhaps it is worth considering the alternative, of generating constants in a ids.rs file. To mirror `parser.c`:
```c

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COMMA = 2,
  anon_sym_COLON = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_module = 5,
  sym_number = 6,
  anon_sym_COLON_COLON = 7,
  anon_sym_SQUOTE = 8,
  anon_sym_state = 9,
  anon_sym_gen = 10,
  anon_sym_PLUS = 11,
  anon_sym_DASH = 12,
  anon_sym_STAR = 13,
  anon_sym_BANG = 14,
  anon_sym_PIPE = 15,
  anon_sym_AMP = 16,
  anon_sym_CARET = 17,
  anon_sym_EQ_EQ = 18,
  .....
  sym_single_line_comment = 41,
  sym_multi_line_comment = 42,
  sym_source_file = 43,
  sym__comma = 44,
  sym_interface_ports = 45,
  sym_declaration_list = 46,
  sym_module = 47,
  sym_global_identifier = 48,
  sym_array_type = 49,
  sym__type = 50,
  sym_latency_specifier = 51,
  sym_declaration = 52,
  sym_unary_op = 53,
  sym_binary_op = 54,
  sym_array_op = 55,
  sym_func_call = 56,
  sym_parenthesis_expression_list = 57,
  sym_parenthesis_expression = 58,
  sym_array_bracket_expression = 59,
  sym__expression = 60,
  aux_sym__linebreak = 61,
  sym_block = 62,
  sym_write_modifiers = 63,
  sym_assign_to = 64,
```

Honestly I like the proc macro approach a bunch more

**Reply by VonTum** [reply]
I referenced this discussion in #3276

**Reply by WillLillis** [reply]
> Maybe I just got it wrong, but in the proc macro's Cargo.toml, I had to make it depend on the parent like this:

Sorry for the confusion, the Cargo.toml in my last comment was for the example program I made using the new crate. The proc macro crate's Cargo.toml looks like this:

```toml
[package]
name = "tree-sitter-c-proc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-c = "0.20.7"
quote = "1.0.36"
syn = "2.0.58"

[lib]
proc-macro = true
```
> I don't quite know if the other maintainers would very much like an extra directory there either, like philosophically rust stuff should go in bindings/rust.

Yeah I could see that too. I haven't worked with too many large projects so I don't have a strong preference either way.

> Honestly I like the proc macro approach a bunch more

Me too. I think it makes more sense to leverage the existing functionality since that's already been extensively tested.

> I referenced this discussion in https://github.com/tree-sitter/tree-sitter/issues/3276

Awesome! Really hope this gets to move forward :)
