### ISSUE TITLE
Weird Cargo.toml generated with `tree-sitter generate`

### ISSUE THREAD

**Issue by osa1** [tree-sitter/tree-sitter#1032]
Version: tree-sitter 0.19.4 (76862e281b3aa5d93b471bfdf903527fec4f9b29)

When I run `tree-sitter generate` I see a `Cargo.toml` generated like this:

```toml
[package]
name = "..."
description = "... grammar for the tree-sitter parsing library"
version = "0.0.1"
keywords = ["incremental", "parsing", "clay"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-javascript"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.17"

[build-dependencies]
cc = "1.0"
```

There are a few problems:

- tree-sitter dependency is 0.17 even though I generated the bindings with 0.19, which depends on lib in the same tree with version 0.19.
- `repository` field points to `tree-sitter-javascript`
