### ISSUE TITLE
Stack overflow with tree-sitter 0.20.8 and 0.20.9 (but works with 0.20.7)

### ISSUE THREAD

**Issue by aibaars** [tree-sitter/tree-sitter#2071]
When testing the tree-sitter-ruby parser on https://github.com/mongodb/mongo-ruby-driver/blob/master/.evergreen/config/standard.yml.erb the parser crashed with a stack overflow. The parser works fine if I downgrade the tree-sitter library to 0.20.7. 

I'm not sure how to debug the problem further. I manually reduced the input to a relatively small test case. Hopefully, it will help you find the cause of the problem:

`Cargo.toml`:
```toml
[package]
name = "test-ruby"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tree-sitter = "=0.20.7"
tree-sitter = "=0.20.8"
tree-sitter-ruby = { git = "https://github.com/tree-sitter/tree-sitter-ruby.git", rev = "7a1921bcfd90e3a04c1ad011059087aaf0168dd4" }
```

`src/main.rs`:
```rust
fn main() {
    let ranges = [
        tree_sitter::Range {
            start_byte: 3,
            end_byte: 7,
            start_point: tree_sitter::Point { row: 0, column: 3 },
            end_point: tree_sitter::Point { row: 0, column: 7 },
        },
        tree_sitter::Range {
            start_byte: 157,
            end_byte: 168,
            start_point: tree_sitter::Point { row: 2, column: 2 },
            end_point: tree_sitter::Point { row: 2, column: 13 },
        },
        tree_sitter::Range {
            start_byte: 172,
            end_byte: 179,
            start_point: tree_sitter::Point { row: 3, column: 2 },
            end_point: tree_sitter::Point { row: 3, column: 9 },
        },
    ];
    let source: [u8; 182] = [
        60, 37, 61, 32, 116, 32, 10, 62, 10, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 10, 60, 37, 124, 61,
        32, 102, 111, 111, 32, 100, 111, 32, 10, 62, 10, 60, 37, 124, 32, 101, 110, 100, 32, 10,
        62, 10, 10,
    ];
    let language = tree_sitter_ruby::language();
    let mut parser = tree_sitter::Parser::new();
    parser.set_language(language).unwrap();
    parser.set_included_ranges(&ranges).unwrap();
    println!("start parsing");
    let _tree = parser.parse(&source, None).expect("Failed to parse file");
    println!("end parsing");
}
```
