### ISSUE TITLE
Ability to manipulate the error cost of a token

### ISSUE THREAD

**Issue by savetheclocktower** [tree-sitter/tree-sitter#2404]
I imagine stuff like this would fall under the umbrella of what @maxbrunsfeld described [in this comment](https://github.com/tree-sitter/tree-sitter/issues/1870#issuecomment-1248659929), but I had a thought just now that I wanted to write down before I forgot it.

In [Pulsar](https://pulsar-edit.dev/) we're running into a situation where

* the user is typing in the middle of a CSS file, thus implicitly introducing temporary parsing errors; and
* the `tree-sitter-css` parser is choosing a catastrophically bad way of recovering from those errors.

Here's the code:

```css
div {
  loremip
}
.sportform input[type=radio]:checked~img {
  border: 4px solid red;
}

@media (max-width: 768px){
  .sportform .box img {
    width: 100px;
    height: 100px;
  }
}
@media (max-width: 512px){
  .sportform .box img {
    width: 60px;
    height: 60px;
    padding: 10px;
  }
}
```

The `loremip` is the part that the user is typing. Ideally the parser would recognize it as something like this, leaving other blocks unaffected:

```
stylesheet
  rule_set
    selectors
      tag_name
    block
      ERROR
        declaration
          property_name
  rule_set
    (...)
```

Instead, for certain lengths of `loremip` — depending, amazingly, on how much content is present later in the file — it decides that the best error recovery strategy would be to _skip over_ the `}` that separates `loremip` from `.sportform input[type=radio]:checked~img`, and act as though those two parts belong to the same CSS selector. The effect of skipping that `}` is that the block started by `div {` never gets finished, and the remainder of the file is considered to be underneath a `block` node with a `MISSING }` at the very end.

I understand why this happens, but this is a situation in which the parser is vastly underestimating the “cost” of skipping that brace. If there were some way to annotate the `grammar.js` with hints about which tokens are cheap to skip and which ones are extremely expensive to skip, I think that'd give parser authors a lot of control for not much effort:

```js
{
  // ...
  block: $ => seq('{',
    repeat($._block_item),
    optional(alias($.last_declaration, $.declaration)),
    error_cost(500, '}')
  ),
  // ...
}
```

I'm sure it's not as simple as I'm describing, but conceptually it seems similar to computing dynamic precedence.
