### ISSUE TITLE
`ts_record_realloc` is not provided in release+debuginfo builds (link-time error)

### ISSUE THREAD

**Issue by fasterthanlime** [tree-sitter/tree-sitter#757]
With rustc 1.47, with a release build, I'm getting tons of linker errors related to `ts_record_realloc` and friends.

  * tree-sitter version: 0.17.0
  * tree-sitter-highlight version: 0.3.0
  * OS: Linux (ArchLinux on WSL2)

```
  = note: /usr/sbin/ld: /home/amos/ftl/futile/target/release/deps/libtree_sitter-298d031b2e4e0adc.rlib(lib.o): in function `ts_realloc':
/home/amos/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-0.17.0/src/././././././alloc.h:29: undefined reference to `ts_record_realloc'
/usr/sbin/ld: /home/amos/ftl/futile/target/release/deps/libtree_sitter-298d031b2e4e0adc.rlib(lib.o): in function `ts_calloc':
/home/amos/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-0.17.0/src/././././././alloc.h:25: undefined reference to `ts_record_calloc'
(etc.)
```

Extract of `Cargo.toml`:

```toml
[profile.release]
debug = 1 # less debug info
incremental = true # faster recompiles

[profile.dev.package."*"]
opt-level = 2

[dependencies]
tree-sitter-highlight = "0.3.0"
tree-sitter-collection = { git = "https://github.com/fasterthanlime/tree-sitter-collection", rev = "9fc44e34047da3fefe2faf91f9359a4374097286" }
tree-sitter = "0.17.0"
```

Here's a link to the [full Cargo.toml](https://gist.github.com/fasterthanlime/984c03511cb1ae93624b7a57e7d3e11b).

Cargo invocation:

```shell
$ cargo build --release
```

I'm seeing similar errors with both GNU ld and lld.

Note that debug builds (just `cargo build`) build and link just fine.

Unfortunately my repository is closed-source, but if someone wants to take a look I can add them to the private repo for a repro. (I realize that's not ideal at all).

Also note that  checking out `tree-sitter` and compiling it in release mode works fine on my machine.

I'm thinking something in [binding_rust/util.rs](https://github.com/tree-sitter/tree-sitter/blob/857a9ed07b983e2e6cff6dc851fcf9b37aec8e5a/lib/binding_rust/util.rs) is a bit too smart, and breaks sometimes, but I can't really tell what to do about it right now.

Thanks for taking a look ✨
